### ISSUE TITLE
[Immersive Subtitles] Dynamic Surroundings Support?

### ISSUE THREAD

**Issue by RaptaG** [Hebgbs/minecraftMods#2]
It would be a nice addition..

Also 2 bugs I noticed:
1. Presence Footsteps "Grass rustles" has an upside down G before its text
2. `pack.mcmeta` says in the description "1.16.3" instead of "1.18.1"

**Comment by Hebgbs** [comment]
I will resolve these problems in a bit. Thanks for letting me know!

As for the upside-down G, that's entirely my fault with bad file editing practices and shenanigans using upside-down text. Big whoopsie.

**Comment by RaptaG** [comment]
Any thoughts for Dynamic Surroundings?

**Comment by RaptaG** [comment]
I fixed them in my installation and I also noticed that the upside-down G is in "Gravel crunches" too

**Comment by Hebgbs** [comment]
I'll release a formal update soon. Like, if you want to make your own riff of it for now, it's basically the subtitle, with §_x_§o; _x_ being the colour, often 7 or 8 for lower-priority notifications, and anything else depending on context.

You also have to remember, I support every English sub, not just `en_us`. So that — composing different subs for different languages — takes time, and I still fail at doing it justice compared to default subs most times.

**Comment by RaptaG** [comment]
I've seen how to change Minecraft's font format and it should be easy to apply it all the .json locale files by copying and pasting the format, since before the language there's the subtitle specification, which is in English.. I'll do my best, when I find some free time at least 😅

**Comment by RaptaG** [comment]
OK! The pack is ready, but the mod itself (DynamicSurroundings) support only `en_us`, so I only modified the `en_us.json`.

[Immersive Subtitles.zip](https://github.com/Hebgbs/minecraftMods/files/8136674/Immersive.Subtitles.zip)
